BASE_DIR="data"
IRC_HOST="atw.irc.hu"
IRC_PORT="6667"
IRC_NICK="magnus23"
IRC_CHAN="#hspbp"
IRC_CONNECTIONS="$BASE_DIR/connections"

QUOTES="$BASE_DIR/quotes.txt"
MESSAGES="$BASE_DIR/messages"
EVENTS="$BASE_DIR/events"
